@echo off
echo Starting Interview Assistant Backend...
echo Activating virtual environment...
call C:\venvs\interview-assistant-313\Scripts\activate.bat
echo Virtual environment activated
echo Starting uvicorn server...
uvicorn app.main:app --reload --reload-dir app --host 0.0.0.0 --port 8001 --reload-exclude "venv/*" --reload-exclude ".venv/*" --reload-exclude "**/__pycache__/*" --reload-exclude "*.pyc" --reload-exclude "node_modules/*"
